-- file: V7__kyc_tables.sql

-- KYC SUBMISSIONS
CREATE TABLE IF NOT EXISTS kyc_submissions
(
    id UUID PRIMARY KEY,                -- generated by app
    user_id UUID NOT NULL,              -- FK ke users (app-managed)
    full_name VARCHAR(255) NOT NULL,
    date_of_birth DATE NOT NULL,
    nationality VARCHAR(100) NOT NULL,
    id_type varchar(50) NOT NULL, -- ID_TYPE_KTP, ID_TYPE_KK, ID_TYPE_PASPORT
    id_number_encrypted TEXT NOT NULL,  -- ciphertext dari aplikasi
    address TEXT,
    status varchar(50) NOT NULL DEFAULT 'PENDING', -- UNVERIFIED, PENDING, VERIFIED, REJECTED

    -- submission fields
    submitted_at TIMESTAMPTZ,
    reviewed_at TIMESTAMPTZ,
    reviewed_by UUID,
    rejection_reason TEXT,
    expires_at TIMESTAMPTZ,

    -- audit fields
    created_at TIMESTAMPTZ   NOT NULL DEFAULT now(),
    created_by UUID,
    updated_at TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_by UUID,
    deleted_at TIMESTAMPTZ,
    deleted_by UUID
);
CREATE INDEX idx_kyc_submissions_user_id ON kyc_submissions(user_id);
CREATE INDEX idx_kyc_submissions_status ON kyc_submissions(status);
CREATE INDEX idx_kyc_submissions_created_at ON kyc_submissions(created_at);

-- KYC DOCUMENTS
CREATE TABLE kyc_documents (
    id UUID PRIMARY KEY,                -- generated by app
    kyc_submission_id UUID NOT NULL REFERENCES kyc_submissions(id) ON DELETE CASCADE,
    doc_type varchar(100) NOT NULL, -- DOC_TYPE_KTP, DOC_TYPE_KK, DOC_TYPE_PASPORT
    file_url TEXT NOT NULL,             -- URL/path di cloud storage (S3/GCS)
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_kyc_documents_submission_id ON kyc_documents(kyc_submission_id);
